$(document).ready(function(){
    $("#hmb").click(function(){
        $("#mb").slideToggle();
    });
    $("#hcpu").click(function(){
        $("#cpu").slideToggle();
    });
    $("#hhd").click(function(){
        $("#hd").slideToggle();
    });
    $("#hram").click(function(){
        $("#ram").slideToggle();
    });
    $("#hpsu").click(function(){
        $("#psu").slideToggle();
    });
    $("#hvc").click(function(){
        $("#vc").slideToggle();
    });
});
